# =========================
# Frontend HTTP (временно, для выпуска сертификата)
# =========================
server {

    server_name simbeauty.ru www.simbeauty.ru;

    root /var/www/simbeauty;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/simbeauty.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/simbeauty.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

    server {
        if ($host = www.simbeauty.ru) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        if ($host = simbeauty.ru) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name simbeauty.ru www.simbeauty.ru;
    return 404; # managed by Certbot
}
