# =========================
# Frontend HTTPS
# =========================
server {
    server_name simbeauty.ru www.simbeauty.ru;

    root /var/www/simbeauty;
    index index.html;

    location / {
        try_files $uri/index.html $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    listen 443 ssl;
    listen [::]:443 ssl;

}

# =========================
# Frontend HTTP -> HTTPS
# =========================
server {
    listen 80;
    listen [::]:80;

    server_name simbeauty.ru www.simbeauty.ru;

    return 301 https://$host$request_uri;
}